\clearpage
## Class 1: Equally likely events

### Introduction 

Probability is used to quantify uncertainty in the real world. Consider the following examples.

1. Roll a pair of dice, then the probability of outcome being a pair of sixes is $\dfrac{1}{36}$. On the other hand the probability of a total score of 11 is $\dfrac{1}{18}$. This statement was not obvious to the first mathematicians to study probability.
2. The probability of detecting an electron at varying locations in the two slit experiment. 
3. A lottery winner is accused of cheating based on the improbability of winning. At the trial, the prosecutor calculates the (very small) probability of winning the lottery without cheating and argues that this is the chance of innocence. Should the jury find this person guilty?
4. A crime-scene DNA sample is compared against a database of 20,000 people. A match is found, that person is accused. At his trial, it is testified that the probability that two DNA profiles matching by chance is only 1 in 10,000. Based on this evidence, should the jury find this man guilty?
5. During a trial, it is claimed that, for an affluent non-smoking family, the probability of a single cot death is 1 in 8,543, so the probability of two cot deaths in the same family is around "1 in 73 million" (8543 $\times$ 8543). Given that there are around 700,000 live births in Britain each year, an expert medical witness argues that a double cot death would be expected to occur once every hundred years. Based on this evidence, should the jury convict?

For a real life activity with an uncertain outcome, we build a mathematical model or representation, within which we calculate mathematical probabilities. These are then interpreted as descriptions of the uncertainty in the real world.

#### Interpreting probability {-}

How do we interpret what a probabilistic statement says about the real world? 

- _Frequentist interpretation_ In the frequentist interpretation we consider many repetitions of the activity with the uncertain outcome, and then there is some characteristic frequency with which a particular outcome tends to occur. This is known as the phenomenon of _statistical regularity_. For example in 36,000,000 rolls of dice we expect to see approximately 1,000,000 occurrences of double sixes. But note that the probability of getting exactly 1,000,000 sixes is actually very low, and there is even the possibility, although it is extremely unlikely indeed, of every roll resulting in a double six. So it's actually not straightforward to describe precisely what `statistical regularity' means. 
- _Bayesian or subjective interpretation_ An alternative interpretation is called Bayesian or subjective. This is more appropriate if it is not sensible to imagine repetitions. According to this interpretation probability quantifies a belief about uncertainty that can be tested by considering bets: would you rather bet on a situation happening or on rolling 9 or less on a pair of dice? However, different individuals may have different beliefs, and so this interpretation has the downside that it's not objective.

In order to build mathematical models for uncertainty, we formalise the setting so that  an experiment with a set of possible outcomes, one and only one of which will occur when the experiment is conducted.

#### Familiar examples in a formal setting {-}

Previous academic encounters with probability focus on the idea that probability is a ratio between _favourable outcomes_ and _possible outcomes_. We want to create formal mathematical models that codify outcomes, but the idea of "favourable outcomes" and "possible outcomes" is not precise enough and needs revisiting. One of the conceptual issues when revisiting establish methods and providing a rigorous reformulation is that it can seem that nothing is achieved. During the formalisation process, situation will arise that the _old_ setting cannot resolve.

:::{.definition}
The _sample space_, usually denoted by $\Omega$, is a set whose elements, called _sample points_, correspond to the possible outcomes of the experiment being considered.
:::


Choosing a sample space is about mathematically encoding the possible outcomes of the experiment.

:::{.example}
Determine the sample space and illustrate a sample point for the following.

1. Roll a pair of (standard) dice, where we can distinguish the dice and both contain 1 to 6 on their six faces.

2. More generally, roll a die $n$ times. 
:::


:::{.solution}
&nbsp;

1. Assuming the dice can be distinguished we can take  $\Omega = \{1, 2, 3, 4, 5, 6\}^2$ . A sample point  $\omega = (i, j)$ corresponds to the outcome that the roll on the first die results in $i$ and that on the second dice $j$.

2. We can take  $\Omega = \{1, 2,3, \ldots , 6\}^n$ . Then a sample point is a sequence  $\omega = (\omega_1, \ldots, \omega_n)$ whose terms are integers between 1 and 6. The outcome corresponding to a sample point  is the one in which the score obtained on the $k$th roll of the die is given by $\omega_k$.
:::


:::{.definition}
An _event_ is a property that the outcome of the experiment may or may not have. We identify an event with the subset of  $\Omega$ containing those sample points with the relevant property.
:::


:::{.example}
&nbsp;

1. Consider forty cards that are all labelled. From these cards 7 are labelled $W$, 6 are labelled $X$, 4 are labelled $Y$ and 8 are labelled $Z$. The remainder (15) are labelled using other letters of the alphabet. Suppose a card is drawn (uniformly) at random. Determine a representation for the sample space.

2. Formally write down the event that the randomly selected card is labelled $W$ or $X$.

3. Formally write down the event that the distance of a point selected at random from the unit disc is greater than $\frac{1}{2}$.
:::


:::{.solution}
&nbsp;

1. Note, the representation is not unique.The sample space $\Omega$ contains all card outcomes, but we cannot just use letters to denote outcomes; the set $\{W,W\}= \{W\}$, so we must distinguish the cards to create the sample space. There are many ways to accomplish this, for example, $(W,i)$ denotes the $i$th card labelled $W$, then two different cards $(W,i)$ and $(W,j)$ ($i\neq j$), although labelled identically are distinguished. 

2. This would be the subset of $\Omega$ contains only cards labelled $W$ or $X$ which would correspond to the property that the outcome is a card labelled $W$ or $X$; that is, using the above notation to describe $\Omega$, this event is the set
\begin{align*}
\{ & (W,1), (W,2), (W,3), (W,4), (W,5), (W,6), (W,7), \\
& (X,1), (X,2), (X,3), (X,4), (X,5), (X,6)\}.
\end{align*} 
3. The sample space is $\Omega = \{ (x,y) \in \mathbf{R}^2 :  x^2 + y^2 \leq 1 \}$. The event is the set
\begin{align*}
A &= \left\{ (x,y) \in \mathbf{R}^2 : \frac{1}{2} < \sqrt{ x^2 + y^2} \leq 1 \right\} \\
&= \left\{ (x,y) \in \mathbf{R}^2 : \frac{1}{4} < x^2 + y^2 \leq 1 \right\}.
\end{align*}
:::

Making an identification between a subset and the property that it represents allows us to manipulate events with set operations. There is a "dictionary":

Event as a set        | Events as properties of the outcome 
|---------------------|-------------------------------------|
|$A\cup B$            |  At least one of $A$ or $B$ occurs 
|$A\cap B$            |$A$ and $B$ both occur 
|$A^c$                |$A$ does not occur 
|$A\subseteq B$       |If $A$ occurs, then $B$ occurs
|$A \setminus B$      |$A$ occurs by $B$ does not.
|$A\cap B = \emptyset$|$A$ and $B$ are disjoint or mutally exclusive

You are asked to recall the following set properties. In the following $A$, $B$, $C$ and $A_1, A_2, \ldots$ are sets.

- *Commutative law* $A \cup B = B \cup A$, $A\cap B = B \cap A$.
- *Associative law* $A \cup (B \cup C) = (A \cup B) \cup C$, $A \cap (B \cap C) = (A \cap B) \cap C$.
- *Distributive law* $A \cup (B \cap C) = (A \cup B) \cap (A \cup C)$, $A \cap (B \cup C) = (A \cap B) \cup (A \cap C)$.
- *De Morgan's laws* $(A \cap B)^c = A^c \cup B^c$, $(A \cup B)^c =A^c \cap B^c$. More generally
\[
\left(\bigcap_{i=1}^{\infty} A_i\right)^c = \left(\bigcup_{i=1}^{\infty} A_i^c\right)\quad 
\left(\bigcup_{i=1}^{\infty} A_i\right)^c = \left(\bigcap_{i=1}^{\infty} A_i^c\right)
\]


:::{.example}
Consider the throw of two standard fair six-sided dice one is red and one is green. (So the dice are numbered 1 to 6.) Let $\Omega$ be the sample space. Let $A$ be the event that the sum of the numbers on the two dice is 7. Let $B$ be the event that the number shown on the green die is less than or equal to 3.

Write down using suitable set-operations

1. The sum of the two dice is 7 and the green die shows no more than 3.

2. The sum of the two dice is not 7 and the green die shows more than 3.
:::


:::{.solution}

1. This is the event $A \cap B$.

2. This is the event $A^c \cap B^c$.
:::


### Equally likely events

Let $A$ and $B$ be events. We say that $A$ and $B$ are equally likely if $\mathbf{P}(A) = \mathbf{P}(B)$.

:::{.definition}
In situations where $\Omega$ is a finite set, and every outcome is considered equally likely (for reasons of symmetry typically) we define the probability of an event $A\subseteq \Omega$ to be
\[
\mathbf{P}(A) = \frac{|A|}{|\Omega|}
\]
where $|A|$ denotes the number of sample points belonging to $A$. Such probabilities are called the uniform probabilities on $\Omega$.
:::

:::{.example}
Consider rolling a dice $n$ times. The sample space  $\Omega = \{1, 2, \ldots , 6\}^n$ contains $6^n$ sample points.

1. Determine the probability that the $k$th roll of the die results in a 6.

2. Determine the probability that at least one roll results in a 6.
:::


:::{.solution}
&nbsp;

1. For $k = 1, 2,\ldots , n$ let $A_k = \{ \omega = (\omega_1 , \omega_2 , \ldots , \omega_n )  : \omega_k = 6\}$. This is the event that $k$th roll of the die results in a 6. We have $|A_k | = 6^{n-1}$ (there are $n-1$ free choices), and taking the probabilities to be uniform we have
\[
\mathbf{P}(A_k ) = \frac{|A_k |}{\Omega} = \frac{6^{n-1}}{6^n} = \frac{1}{6},
\]
as we would expect.

2. For $k = 1, 2,\ldots , n$ let $A_k = \{ \omega = (\omega_1 , \omega_2 , \ldots , \omega_n )  : \omega_k = 6\}$. The set $B=\displaystyle\bigcup_{k=1}^n A_k$ is the event that at least one roll results in a 6. We must determine 
\[
\mathbf{P}\left(B \right) 
= 
\frac{\left|B \right|}{|\Omega|}.
\]
Note that that number of elements of $\Omega$ not in $B$ is
\[
B^c = 
\left(
\bigcup_{k=1}^n A_k
\right)^c
=
\bigcap_{k=1}^n A_k^c.
\]
The event $A_k^c$ is the event that the $k$th roll is not a 6 and thus $\displaystyle\bigcap_{k=1}^n A_k^c$ is the event that no roll results in a 6. The number of sample points is $5^n$; that is, there are $n$ choices of which we may select $1,2,3,4,5$. Thus
\[
\mathbf{P} \left(
B
\right)
=
\frac{|\Omega| - \left|B^c \right|}{|\Omega|}
=
\frac{6^n - 5^n}{6^n} = 1 - \left( \frac{5}{6} \right)^{n}.
\]
:::
