\clearpage
### Class 1: Exercises

:::{.exercise #cards40}
Consider forty cards that are all labelled. From these cards 7 are labelled $W$, 6 are labelled $X$, 4 are labelled $Y$ and 8 are labelled $Z$. The remainder (15) are labelled using other letters of the alphabet. Suppose a card is drawn (uniformly) at random. Formally write down the following events:

1. The randomly selected card shows a "W" and "X".

2. The randomly selected card does not show a "W".
:::

:::{.exercise #dice1}
Consider a (standard) dice and roll the dice once. Formally write down the event: if the dice shows a "2" or "4", then the dice also shows an even number.
:::

:::{.exercise #dice2}
Suppose that a fair die is rolled once. Let 

1. $A$ be the event that an even number is obtained.

2.$B$ be the event that an odd number is obtained.

3. $C$ be the event that a prime number is obtained.

4. $D$ be the event that the number obtained is divisible by 3.

Let $E_k$ be the event that the number `k' is obtained, where $k=1,2, \ldots 6$. Express $E_k$, for $k=1, 2, \ldots 6$ in terms of the events $A$, $B$, $C$ or $D$.
:::

:::{.exercise #dice3}
Consider rolling a dice $n$ times. The sample space  $\Omega = \{1, 2, \ldots , 6\}^n$ contains $6^n$ sample points. Determine the probability that every roll results in a 6.
:::

:::{.exercise #integer}
An integer is selected at random from 1 to 50 inclusive. Determine the probability that the selected integer is divisible by 12. 
:::


