\clearpage
### Class 1: Exercises

:::{.exercise #cards40}
Consider forty cards that are all labelled. From these cards 7 are labelled $W$, 6 are labelled $X$, 4 are labelled $Y$ and 8 are labelled $Z$. The remainder (15) are labelled using other letters of the alphabet. Suppose a card is drawn (uniformly) at random. Formally write down the following events:

1\. The randomly selected card shows a "W" and "X".

2\. The randomly selected card does not show a "W".
:::

:::{.exercise #dice1}
Consider a (standard) dice and roll the dice once. Formally write down the event: if the dice shows a "2" or "4", then the dice also shows an even number.
:::

:::{.exercise #dice2}
Suppose that a fair die is rolled once. Let 

1\. $A$ be the event that an even number is obtained.

2\.$B$ be the event that an odd number is obtained.

3\. $C$ be the event that a prime number is obtained.

4\. $D$ be the event that the number obtained is divisible by 3.

Let $E_k$ be the event that the number `k' is obtained, where $k=1,2, \ldots 6$. Express $E_k$, for $k=1, 2, \ldots 6$ in terms of the events $A$, $B$, $C$ or $D$.
:::

:::{.exercise #dice3}
Consider rolling a dice $n$ times. The sample space  $\Omega = \{1, 2, \ldots , 6\}^n$ contains $6^n$ sample points. Determine the probability that every roll results in a 6.
:::

:::{.exercise #integer}
An integer is selected at random from 1 to 50 inclusive. Determine the probability that the selected integer is divisible by 12. 
:::

### Class 1: Solutions

:::{.proof name="Solution to exercise \@ref(exr:cards40)"}
In some cases there are multiple different, but equivalent answers. Let $A$ be the event the drawn card shows a "W" and $B$ be the event the drawn card shows a "X". 

1\. The event $A\cap B$ is the card show "W" and "X", which cannot occur; that is, $A \cap B = \emptyset\subseteq \Omega$.

2\. The event $A^c$ is the outcome the card does not show a "W".
:::

:::{.proof name="Solution to exercise \@ref(exr:dice1)"}
In this case, $\Omega = \{1, 2, 3, 4, 5, 6\}$. Let $A$ be the event $A=\{2,4\}$ and $B=\{2,4,6\}$; that is, the dice shows an even number. Then $A\subseteq B$; that is, is the event that if the dice shows 2 or 4, then the dice shows an even number.
:::

:::{.proof name="Solution to exercise \@ref(exr:dice2)"}
&nbsp;\
1\. $E_1 = B \setminus C$.

2\. $E_2 = C \setminus B = C \cap A$.

3\. $E_3 = D \setminus A = D \cap B = D \cap C$.

4\. $E_4 = A \setminus (C \cup D)$.

5\. $E_5 = (B \cap C) \setminus D = C \setminus (A \cup D)$.

6\. $E_6 = D \setminus B = D \setminus C = A \cap D$.
:::

:::{.proof name="Solution to exercise \@ref(exr:dice3)"}
The set $\displaystyle\bigcap_{k=1}^n A_k$ is the event that every roll results is a 6. This contains one sample point, namely $\omega = (6,\ldots, 6)$ and
\[
\mathbf{P} \left(
\bigcap_{k=1}^n A_k
\right)
=
\frac{1}{6^n}.
\]
:::

:::{.proof name="Solution to exercise \@ref(exr:integer)"}
The sample space is $\Omega = \{ 1, 2, \ldots, 50 \}$ and $| \Omega | = 50$. The required event is $A = \{ 12, 24, 36, 48 \}$ with $|A| = 4$. Therefore,
\[
\mathbf{P}(A) = \frac{ |A| }{|\Omega|} = \frac{4}{50} = \frac{2}{25}.
\]
:::
