\clearpage
## Chapter 1 consolidation questions


Chapter Consolidation Questions provide additional practice covering the entire chapter. The questions may require you to evaluate information to determine the appropriate approach to solve a problem. For this reason, you may find these questions best saved for revision.


**Chapter outcomes review**

Having reviewed the material and completed the assessment (formative and summative) material, you should be able to:

- Know the definitions of sample space, sample point, event and probability measure.

- Analyse and then formulate problems in terms of sample spaces, events and probability measures.

- Select and apply appropriate theory to determine probabilities.


:::{.exercise #repeatedroll}
Suppose you repeatedly roll a fair six-sided die with numbered faces 1 to 6. Determine the following

a. The probability the $n$th roll produces the first 6.

b. You roll at least one 5 before the first 6.
:::

:::{.exercise #fourplayers}
A game involves four players. Label the players $P_1$, $P_2$, $P_3$ and $P_4$. Each player selects a sequence of heads and tails and then a coin is tossed until one of the selects sequences occurs. The player whose sequence is the first to appear wins. Suppose $P_1$ selects the sequence HHT, $P_2$, THH, $P_3$, TTH and $P_4$, HTT.

a. If only $P_1$ and $P_2$ play, determine the probability that $P_1$ wins.

b. If all four players play together, determine the probabilities of each one winning.
:::

:::{.exercise #cardcollection}
Consider a collection of cards whose faces are labelled $1, 2, \ldots, m$. The cards are shuffled and then spread in a row across a table. Shuffling the cards means we can assume that any card is equally likely to be in any position in the row of cards. 

Determine the probability that at least one card is in the same position as the number on its face.
:::

:::{.exercise #largesquare}
Consider a large square table divided into smaller squares of side length $a>0$. A coin of diameter $2r < a$ is thrown and lands randomly on the table. Probabilities are assigned to events so that they are proportional to the area of the corresponding subset. Determine the probability that

a. The coin falls entirely in the interior of one of the squares;

b. The coin intersects no more than one side of the square.

(Here `randomly' means all landing spots on the table are equally likely.)
:::

:::{.exercise #largesquare2}
Consider a large square table divided into smaller squares of side length $a>0$. A coin of diameter $2r < a$ is thrown and lands randomly on the table. Probabilities are assigned to events so that they are proportional to the area of the corresponding subset. Determine the probability that

a. The coin falls entirely in the interior of one of the squares;

b. The coin intersects no more than one side of the square.

(Here `randomly' means all landing spots on the table are equally likely.)
:::
